### ISSUE TITLE
jQuery 3 Compatibility

### ISSUE THREAD

**Issue by jqueryscript** [brock-eng/JQuery-Animate-OnScroll#1]
Seems like the plugin doesn't work with the latest jQuery 3.x. Any chance to fix that?

**Comment by brock-eng** [comment]
Script should still work as of 3.6.0 - I'm still getting animations to trigger when using the script on my [own site](https://brock-eng.com).  

EDIT: So looks like jQuery 3.x can have issues with the `$(window).on("load"`, (I was getting errors when first loading a page) so the fix is to wrap the entire function and implementation in a `$(window).on("load", function () {` so the script only activates when all images/elements are loaded.  Should be fixed to work with 3.6.0
